<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>reg_log_trafermoney</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>707d4eec-b9b2-4694-97b4-408aa4a66522</testSuiteGuid>
   <testCaseLink>
      <guid>c5e44ef3-cd3d-447a-ac1a-b392a3ba09e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC1_register</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ae11be7e-1daf-480a-8ce6-3db9e1ee6a7c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ae11be7e-1daf-480a-8ce6-3db9e1ee6a7c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullname</value>
         <variableId>a4fb06eb-39d3-4184-a1a5-4f4af43ffa59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ae11be7e-1daf-480a-8ce6-3db9e1ee6a7c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f611f7c7-8b93-4bf7-9153-91d368c941dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ae11be7e-1daf-480a-8ce6-3db9e1ee6a7c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>bc88358f-f11e-4c76-bcc0-5928ff100ee4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ae11be7e-1daf-480a-8ce6-3db9e1ee6a7c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2b540d38-4f2b-4790-a28a-ac586b0b61b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ae11be7e-1daf-480a-8ce6-3db9e1ee6a7c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirmpassword</value>
         <variableId>92767c19-6645-47dc-8ebb-54db491c6e8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76211ab4-62d5-4c2d-9d1c-b3822fc1ecef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC3_fundtransfertoreguseraccount</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f816ee47-a0fa-47bb-9756-7c11a176d538</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f816ee47-a0fa-47bb-9756-7c11a176d538</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullname</value>
         <variableId>93af6ca2-a28a-4eb2-901f-680233a53026</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c519ed65-3aa0-4064-a494-16fa6f3fd865</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC2_login_multipleuser</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3deca1d5-9c50-4c50-904a-be661b8fcfca</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3deca1d5-9c50-4c50-904a-be661b8fcfca</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b8263101-920b-4a68-9328-91a6febe0b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3deca1d5-9c50-4c50-904a-be661b8fcfca</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>273cf01e-d02d-4633-86aa-6df837991c47</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
