<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>topadd</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3cb6ac66-ee02-45f7-b2d2-5f7a7299ff4f</testSuiteGuid>
   <testCaseLink>
      <guid>6382a14d-7bff-4ffb-9903-bc28f424daf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC1_register</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ef91c01b-4ca1-47af-ac6d-8fabb3baa98d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ef91c01b-4ca1-47af-ac6d-8fabb3baa98d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullname</value>
         <variableId>a4fb06eb-39d3-4184-a1a5-4f4af43ffa59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ef91c01b-4ca1-47af-ac6d-8fabb3baa98d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f611f7c7-8b93-4bf7-9153-91d368c941dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ef91c01b-4ca1-47af-ac6d-8fabb3baa98d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>bc88358f-f11e-4c76-bcc0-5928ff100ee4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ef91c01b-4ca1-47af-ac6d-8fabb3baa98d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2b540d38-4f2b-4790-a28a-ac586b0b61b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ef91c01b-4ca1-47af-ac6d-8fabb3baa98d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirmpassword</value>
         <variableId>92767c19-6645-47dc-8ebb-54db491c6e8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10be48f5-2f45-4a45-bbaa-da96c54f5cd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC3_fundtransfertoreguseraccount</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ae6d4c0-aa22-4a4c-9734-91b068c493b9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7ae6d4c0-aa22-4a4c-9734-91b068c493b9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullname</value>
         <variableId>93af6ca2-a28a-4eb2-901f-680233a53026</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f07dc46-26fb-42b4-bb79-7fd1a2989690</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC7_loginnormal</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dad64a40-4cdc-479a-b74d-71d965854ecf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dad64a40-4cdc-479a-b74d-71d965854ecf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>fd8d4cd4-37a3-4b48-af02-90826df7cdab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dad64a40-4cdc-479a-b74d-71d965854ecf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1c170460-6c4a-41b8-8fa8-28bbfd1a65ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cbdbd11-41ad-47f1-a09c-0ee1cba71408</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VBBankTC/TC9_topup</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6da2e754-69e3-4e5c-b915-42ba5cfe6645</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/vbregdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6da2e754-69e3-4e5c-b915-42ba5cfe6645</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>billpayamount</value>
         <variableId>1f1078d4-41cc-440f-ab5a-5bdf2ce127c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6da2e754-69e3-4e5c-b915-42ba5cfe6645</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cardnumber</value>
         <variableId>ab8f41ce-14e4-4e6c-816f-6c53ca7fc592</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6da2e754-69e3-4e5c-b915-42ba5cfe6645</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cardholdername</value>
         <variableId>669ac1a7-0851-40bf-8bca-992bd0f1066d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6da2e754-69e3-4e5c-b915-42ba5cfe6645</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cvv</value>
         <variableId>f3a33510-4cd1-4327-9731-09dfd2e4e86f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
