<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_5</name>
   <tag></tag>
   <elementGuidId>3e134b68-355b-4175-9a11-fd298193ff6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[56]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c624bea3-aa85-4eb3-9dcd-64440bbe2d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-calendar__tile react-calendar__month-view__days__day</value>
      <webElementGuid>e8416e6b-9ee6-4898-a8b6-ed2e29c99b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>700d620e-0dae-4235-a448-03e689da6264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d68475e0-3a5b-4866-9dc0-d7c035964643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-scrollbar __className_703ca4 bg-tertiary&quot;]/main[@class=&quot;min-w-[1240px] overflow-x-scroll bg-primary&quot;]/div[@class=&quot;mainContainer m-auto max-w-[1240px]&quot;]/div[@class=&quot;pt-30 mx-0 relative px-20 xl:px-0 undefined&quot;]/div[@class=&quot;border-none shadow-500 p-20 flex flex-col gap-10 rounded-20 bg-white undefined&quot;]/div[@class=&quot;absolute bg-white rounded-20 max-h-[520px] w-[720px] shadow-500 z-20 top-[175px] left-[600px]&quot;]/div[@class=&quot;relative overflow-y-hidden max-h-[520px] rounded-20&quot;]/div[@class=&quot;react-calendar react-calendar--doubleView desktop mt-50 px-20 xl:my-0 xl:px-20 xl:pt-10&quot;]/div[@class=&quot;react-calendar__viewContainer&quot;]/div[@class=&quot;react-calendar__month-view&quot;]/div[1]/div[1]/div[@class=&quot;react-calendar__month-view__days&quot;]/button[@class=&quot;react-calendar__tile react-calendar__month-view__days__day&quot;]</value>
      <webElementGuid>9c04730f-4398-42c8-a992-559b36c09457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[56]</value>
      <webElementGuid>2238eef0-4f02-4ed8-b9e2-eb2b56e6a339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::button[11]</value>
      <webElementGuid>3cf62722-26dd-4a7f-83cb-b762d265d54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[2]/following::button[11]</value>
      <webElementGuid>43b474f7-41dc-4dd6-8325-6e30863d2904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live'])[1]/preceding::button[32]</value>
      <webElementGuid>d99fd9ad-d849-4544-acb1-37db216508d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Running'])[1]/preceding::button[32]</value>
      <webElementGuid>105f51b0-69c0-406f-9330-0681365abf33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button[11]</value>
      <webElementGuid>32e7e870-ae97-4356-83ed-b28dded83ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '5' or . = '5')]</value>
      <webElementGuid>c87c417b-bc7c-4a30-b140-b88a7ed409a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
