<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_outline-none w-full bg-transparent placeholdertext-disabled pt-3 text-primary placeholderopacity-0 focusplaceholderopacity-100 body-lg text-neutral-800 font-medium pt-5</name>
   <tag></tag>
   <elementGuidId>e9378062-4a62-4a1b-9454-c5a9496d650d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7520378d-c7ed-4ad0-915f-5519d776a36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Destination</value>
      <webElementGuid>5754e87d-df5a-40ea-9911-44c9f553ba2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>32263b09-32c7-465f-87bf-e796763c858e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>autocompleter-input</value>
      <webElementGuid>40dfa593-d30b-4ec1-a8e8-4f98b33e44f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none w-full bg-transparent placeholder:text-disabled pt-3 text-primary placeholder:opacity-0 focus:placeholder:opacity-100 body-lg text-neutral-800 font-medium pt-5</value>
      <webElementGuid>fdc7859f-8244-46f2-8aa5-5fa72fbcf2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;origin-destination-input&quot;)/div[@class=&quot;flex bg-charcoal-40 items-center relative w-full h-[60px] hover:bg-neutral-subtle-over pt-[7.5px] px-20 undefined&quot;]/div[@class=&quot;flex w-full border-transparent border-b-4&quot;]/div[@class=&quot;inline-flex flex-col text-secondary w-full cursor-pointer rounded-l-10 bg-neutral-40 hover:bg-neutral-subtle-over&quot;]/div[@class=&quot;flex relative transition-all group/input pb-2 items-end mt-2&quot;]/div[@class=&quot;flex flex-grow items-center&quot;]/input[@class=&quot;outline-none w-full bg-transparent placeholder:text-disabled pt-3 text-primary placeholder:opacity-0 focus:placeholder:opacity-100 body-lg text-neutral-800 font-medium pt-5&quot;]</value>
      <webElementGuid>cf4cb19f-a8e9-48be-b980-48c4b08f23d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>c8312ee0-ca2c-437b-89a8-9fbcba5229af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='origin-destination-input']/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>88689c72-e9a2-45ab-b1a9-2bdb70bdb13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>182f56fd-a0d6-4851-b212-36071b6043f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Destination' and @type = 'search']</value>
      <webElementGuid>0c119b64-5e02-430a-ba40-a0174721900b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
